In [1]:
import numpy as np

In [10]:
data = np.array([
                 [np.nan,      9,          8], 
                 [9,      np.nan,          7], 
                 [8,           7,     np.nan], 
                 [7,           6,          5]
               ])
print(data)

[[nan  9.  8.]
 [ 9. nan  7.]
 [ 8.  7. nan]
 [ 7.  6.  5.]]


In [11]:
# Filling Values with mean
from sklearn.impute import SimpleImputer
mean_values = SimpleImputer(strategy='mean')
data1 = mean_values.fit_transform(data)
print(data1)

[[8.         9.         8.        ]
 [9.         7.33333333 7.        ]
 [8.         7.         6.66666667]
 [7.         6.         5.        ]]


In [12]:
# Filling Values with median
from sklearn.impute import SimpleImputer
median_values = SimpleImputer(strategy='median')
data2 = median_values.fit_transform(data)
print(data2)

[[8. 9. 8.]
 [9. 7. 7.]
 [8. 7. 7.]
 [7. 6. 5.]]


In [13]:
# Filling values with most frequent values
from sklearn.impute import SimpleImputer
most_frequent = SimpleImputer(strategy='most_frequent')
data3 = most_frequent.fit_transform(data)
print(data3)

[[7. 9. 8.]
 [9. 6. 7.]
 [8. 7. 5.]
 [7. 6. 5.]]
